
interface _GlobalComponents {
      'UiAccordion': typeof import("../components/Ui/accordion/Accordion.vue")['default']
    'UiAccordionContent': typeof import("../components/Ui/accordion/AccordionContent.vue")['default']
    'UiAccordionItem': typeof import("../components/Ui/accordion/AccordionItem.vue")['default']
    'UiAccordionTrigger': typeof import("../components/Ui/accordion/AccordionTrigger.vue")['default']
    'UiAlertDialog': typeof import("../components/Ui/alert-dialog/AlertDialog.vue")['default']
    'UiAlertDialogAction': typeof import("../components/Ui/alert-dialog/AlertDialogAction.vue")['default']
    'UiAlertDialogCancel': typeof import("../components/Ui/alert-dialog/AlertDialogCancel.vue")['default']
    'UiAlertDialogContent': typeof import("../components/Ui/alert-dialog/AlertDialogContent.vue")['default']
    'UiAlertDialogDescription': typeof import("../components/Ui/alert-dialog/AlertDialogDescription.vue")['default']
    'UiAlertDialogFooter': typeof import("../components/Ui/alert-dialog/AlertDialogFooter.vue")['default']
    'UiAlertDialogHeader': typeof import("../components/Ui/alert-dialog/AlertDialogHeader.vue")['default']
    'UiAlertDialogTitle': typeof import("../components/Ui/alert-dialog/AlertDialogTitle.vue")['default']
    'UiAlertDialogTrigger': typeof import("../components/Ui/alert-dialog/AlertDialogTrigger.vue")['default']
    'UiAlert': typeof import("../components/Ui/alert/Alert.vue")['default']
    'UiAlertDescription': typeof import("../components/Ui/alert/AlertDescription.vue")['default']
    'UiAlertTitle': typeof import("../components/Ui/alert/AlertTitle.vue")['default']
    'UiAspectRatio': typeof import("../components/Ui/aspect-ratio/AspectRatio.vue")['default']
    'UiAvatar': typeof import("../components/Ui/avatar/Avatar.vue")['default']
    'UiAvatarFallback': typeof import("../components/Ui/avatar/AvatarFallback.vue")['default']
    'UiAvatarImage': typeof import("../components/Ui/avatar/AvatarImage.vue")['default']
    'UiBadge': typeof import("../components/Ui/badge/Badge.vue")['default']
    'UiBreadcrumb': typeof import("../components/Ui/breadcrumb/Breadcrumb.vue")['default']
    'UiBreadcrumbEllipsis': typeof import("../components/Ui/breadcrumb/BreadcrumbEllipsis.vue")['default']
    'UiBreadcrumbItem': typeof import("../components/Ui/breadcrumb/BreadcrumbItem.vue")['default']
    'UiBreadcrumbLink': typeof import("../components/Ui/breadcrumb/BreadcrumbLink.vue")['default']
    'UiBreadcrumbList': typeof import("../components/Ui/breadcrumb/BreadcrumbList.vue")['default']
    'UiBreadcrumbPage': typeof import("../components/Ui/breadcrumb/BreadcrumbPage.vue")['default']
    'UiBreadcrumbSeparator': typeof import("../components/Ui/breadcrumb/BreadcrumbSeparator.vue")['default']
    'UiButton': typeof import("../components/Ui/button/Button.vue")['default']
    'UiCalendar': typeof import("../components/Ui/calendar/Calendar.vue")['default']
    'UiCalendarCell': typeof import("../components/Ui/calendar/CalendarCell.vue")['default']
    'UiCalendarCellTrigger': typeof import("../components/Ui/calendar/CalendarCellTrigger.vue")['default']
    'UiCalendarGrid': typeof import("../components/Ui/calendar/CalendarGrid.vue")['default']
    'UiCalendarGridBody': typeof import("../components/Ui/calendar/CalendarGridBody.vue")['default']
    'UiCalendarGridHead': typeof import("../components/Ui/calendar/CalendarGridHead.vue")['default']
    'UiCalendarGridRow': typeof import("../components/Ui/calendar/CalendarGridRow.vue")['default']
    'UiCalendarHeadCell': typeof import("../components/Ui/calendar/CalendarHeadCell.vue")['default']
    'UiCalendarHeader': typeof import("../components/Ui/calendar/CalendarHeader.vue")['default']
    'UiCalendarHeading': typeof import("../components/Ui/calendar/CalendarHeading.vue")['default']
    'UiCalendarNextButton': typeof import("../components/Ui/calendar/CalendarNextButton.vue")['default']
    'UiCalendarPrevButton': typeof import("../components/Ui/calendar/CalendarPrevButton.vue")['default']
    'UiCarousel': typeof import("../components/Ui/carousel/Carousel.vue")['default']
    'UiCarouselContent': typeof import("../components/Ui/carousel/CarouselContent.vue")['default']
    'UiCarouselItem': typeof import("../components/Ui/carousel/CarouselItem.vue")['default']
    'UiCarouselNext': typeof import("../components/Ui/carousel/CarouselNext.vue")['default']
    'UiCarouselPrevious': typeof import("../components/Ui/carousel/CarouselPrevious.vue")['default']
    'UiCarouselInterface': typeof import("../components/Ui/carousel/interface")['default']
    'UiCarouselUseCarousel': typeof import("../components/Ui/carousel/useCarousel")['default']
    'UiCheckbox': typeof import("../components/Ui/checkbox/Checkbox.vue")['default']
    'UiChip': typeof import("../components/Ui/chip/Chip.vue")['default']
    'UiDivider': typeof import("../components/Ui/divider/divider.vue")['default']
    'UiDropfile': typeof import("../components/Ui/dropfile/Dropfile.vue")['default']
    'UiHoverCard': typeof import("../components/Ui/hover-card/HoverCard.vue")['default']
    'UiHoverCardContent': typeof import("../components/Ui/hover-card/HoverCardContent.vue")['default']
    'UiHoverCardTrigger': typeof import("../components/Ui/hover-card/HoverCardTrigger.vue")['default']
    'UiInput': typeof import("../components/Ui/input/Input.vue")['default']
    'UiLabel': typeof import("../components/Ui/label/Label.vue")['default']
    'UiPopover': typeof import("../components/Ui/popover/Popover.vue")['default']
    'UiPopoverContent': typeof import("../components/Ui/popover/PopoverContent.vue")['default']
    'UiPopoverTrigger': typeof import("../components/Ui/popover/PopoverTrigger.vue")['default']
    'UiSelect': typeof import("../components/Ui/select/Select.vue")['default']
    'UiSelectContent': typeof import("../components/Ui/select/SelectContent.vue")['default']
    'UiSelectGroup': typeof import("../components/Ui/select/SelectGroup.vue")['default']
    'UiSelectItem': typeof import("../components/Ui/select/SelectItem.vue")['default']
    'UiSelectItemText': typeof import("../components/Ui/select/SelectItemText.vue")['default']
    'UiSelectLabel': typeof import("../components/Ui/select/SelectLabel.vue")['default']
    'UiSelectScrollDownButton': typeof import("../components/Ui/select/SelectScrollDownButton.vue")['default']
    'UiSelectScrollUpButton': typeof import("../components/Ui/select/SelectScrollUpButton.vue")['default']
    'UiSelectSeparator': typeof import("../components/Ui/select/SelectSeparator.vue")['default']
    'UiSelectTrigger': typeof import("../components/Ui/select/SelectTrigger.vue")['default']
    'UiSelectValue': typeof import("../components/Ui/select/SelectValue.vue")['default']
    'UiSeparator': typeof import("../components/Ui/separator/Separator.vue")['default']
    'UiToast': typeof import("../components/Ui/toast/Toast.vue")['default']
    'UiToastAction': typeof import("../components/Ui/toast/ToastAction.vue")['default']
    'UiToastClose': typeof import("../components/Ui/toast/ToastClose.vue")['default']
    'UiToastDescription': typeof import("../components/Ui/toast/ToastDescription.vue")['default']
    'UiToastProvider': typeof import("../components/Ui/toast/ToastProvider.vue")['default']
    'UiToastTitle': typeof import("../components/Ui/toast/ToastTitle.vue")['default']
    'UiToastViewport': typeof import("../components/Ui/toast/ToastViewport.vue")['default']
    'UiToastToaster': typeof import("../components/Ui/toast/Toaster.vue")['default']
    'UiToastUseToast': typeof import("../components/Ui/toast/use-toast")['default']
    'NuxtWelcome': typeof import("../node_modules/.pnpm/@nuxt+ui-templates@1.3.3/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Form': typeof import("vee-validate")['Form']
    'FormField': typeof import("vee-validate")['Field']
    'Pagination': typeof import("radix-vue")['PaginationRoot']
    'PaginationList': typeof import("radix-vue")['PaginationList']
    'PaginationListItem': typeof import("radix-vue")['PaginationListItem']
    'Accordion': typeof import("../components/ui/accordion/index")['Accordion']
    'AccordionContent': typeof import("../components/ui/accordion/index")['AccordionContent']
    'AccordionItem': typeof import("../components/ui/accordion/index")['AccordionItem']
    'AccordionTrigger': typeof import("../components/ui/accordion/index")['AccordionTrigger']
    'Alert': typeof import("../components/ui/alert/index")['Alert']
    'AlertTitle': typeof import("../components/ui/alert/index")['AlertTitle']
    'AlertDescription': typeof import("../components/ui/alert/index")['AlertDescription']
    'AlertDialog': typeof import("../components/ui/alert-dialog/index")['AlertDialog']
    'AlertDialogTrigger': typeof import("../components/ui/alert-dialog/index")['AlertDialogTrigger']
    'AlertDialogContent': typeof import("../components/ui/alert-dialog/index")['AlertDialogContent']
    'AlertDialogHeader': typeof import("../components/ui/alert-dialog/index")['AlertDialogHeader']
    'AlertDialogTitle': typeof import("../components/ui/alert-dialog/index")['AlertDialogTitle']
    'AlertDialogDescription': typeof import("../components/ui/alert-dialog/index")['AlertDialogDescription']
    'AlertDialogFooter': typeof import("../components/ui/alert-dialog/index")['AlertDialogFooter']
    'AlertDialogAction': typeof import("../components/ui/alert-dialog/index")['AlertDialogAction']
    'AlertDialogCancel': typeof import("../components/ui/alert-dialog/index")['AlertDialogCancel']
    'AspectRatio': typeof import("../components/ui/aspect-ratio/index")['AspectRatio']
    'Avatar': typeof import("../components/ui/avatar/index")['Avatar']
    'AvatarImage': typeof import("../components/ui/avatar/index")['AvatarImage']
    'AvatarFallback': typeof import("../components/ui/avatar/index")['AvatarFallback']
    'Breadcrumb': typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
    'BreadcrumbEllipsis': typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
    'BreadcrumbItem': typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
    'BreadcrumbLink': typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
    'BreadcrumbList': typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
    'BreadcrumbPage': typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
    'BreadcrumbSeparator': typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
    'Button': typeof import("../components/ui/button/index")['Button']
    'Calendar': typeof import("../components/ui/calendar/index")['Calendar']
    'CalendarCell': typeof import("../components/ui/calendar/index")['CalendarCell']
    'CalendarCellTrigger': typeof import("../components/ui/calendar/index")['CalendarCellTrigger']
    'CalendarGrid': typeof import("../components/ui/calendar/index")['CalendarGrid']
    'CalendarGridBody': typeof import("../components/ui/calendar/index")['CalendarGridBody']
    'CalendarGridHead': typeof import("../components/ui/calendar/index")['CalendarGridHead']
    'CalendarGridRow': typeof import("../components/ui/calendar/index")['CalendarGridRow']
    'CalendarHeadCell': typeof import("../components/ui/calendar/index")['CalendarHeadCell']
    'CalendarHeader': typeof import("../components/ui/calendar/index")['CalendarHeader']
    'CalendarHeading': typeof import("../components/ui/calendar/index")['CalendarHeading']
    'CalendarNextButton': typeof import("../components/ui/calendar/index")['CalendarNextButton']
    'CalendarPrevButton': typeof import("../components/ui/calendar/index")['CalendarPrevButton']
    'Carousel': typeof import("../components/ui/carousel/index")['Carousel']
    'CarouselContent': typeof import("../components/ui/carousel/index")['CarouselContent']
    'CarouselItem': typeof import("../components/ui/carousel/index")['CarouselItem']
    'CarouselPrevious': typeof import("../components/ui/carousel/index")['CarouselPrevious']
    'CarouselNext': typeof import("../components/ui/carousel/index")['CarouselNext']
    'CarouselApi': typeof import("../components/ui/carousel/index")['CarouselApi']
    'Checkbox': typeof import("../components/ui/checkbox/index")['Checkbox']
    'Chip': typeof import("../components/ui/chip/index")['Chip']
    'HoverCard': typeof import("../components/ui/hover-card/index")['HoverCard']
    'HoverCardTrigger': typeof import("../components/ui/hover-card/index")['HoverCardTrigger']
    'HoverCardContent': typeof import("../components/ui/hover-card/index")['HoverCardContent']
    'Input': typeof import("../components/ui/input/index")['Input']
    'Label': typeof import("../components/ui/label/index")['Label']
    'Popover': typeof import("../components/ui/popover/index")['Popover']
    'PopoverTrigger': typeof import("../components/ui/popover/index")['PopoverTrigger']
    'PopoverContent': typeof import("../components/ui/popover/index")['PopoverContent']
    'Select': typeof import("../components/ui/select/index")['Select']
    'SelectValue': typeof import("../components/ui/select/index")['SelectValue']
    'SelectTrigger': typeof import("../components/ui/select/index")['SelectTrigger']
    'SelectContent': typeof import("../components/ui/select/index")['SelectContent']
    'SelectGroup': typeof import("../components/ui/select/index")['SelectGroup']
    'SelectItem': typeof import("../components/ui/select/index")['SelectItem']
    'SelectItemText': typeof import("../components/ui/select/index")['SelectItemText']
    'SelectLabel': typeof import("../components/ui/select/index")['SelectLabel']
    'SelectSeparator': typeof import("../components/ui/select/index")['SelectSeparator']
    'SelectScrollUpButton': typeof import("../components/ui/select/index")['SelectScrollUpButton']
    'SelectScrollDownButton': typeof import("../components/ui/select/index")['SelectScrollDownButton']
    'Separator': typeof import("../components/ui/separator/index")['Separator']
    'Toaster': typeof import("../components/ui/toast/index")['Toaster']
    'Toast': typeof import("../components/ui/toast/index")['Toast']
    'ToastViewport': typeof import("../components/ui/toast/index")['ToastViewport']
    'ToastAction': typeof import("../components/ui/toast/index")['ToastAction']
    'ToastClose': typeof import("../components/ui/toast/index")['ToastClose']
    'ToastTitle': typeof import("../components/ui/toast/index")['ToastTitle']
    'ToastDescription': typeof import("../components/ui/toast/index")['ToastDescription']
    'ToastProvider': typeof import("../components/ui/toast/index")['ToastProvider']
    'ColorScheme': typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@3.4.1/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'Icon': typeof import("../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_vite@5.2.11_vue@3.4.26/node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'IconCSS': typeof import("../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_vite@5.2.11_vue@3.4.26/node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'NuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyUiAccordion': typeof import("../components/Ui/accordion/Accordion.vue")['default']
    'LazyUiAccordionContent': typeof import("../components/Ui/accordion/AccordionContent.vue")['default']
    'LazyUiAccordionItem': typeof import("../components/Ui/accordion/AccordionItem.vue")['default']
    'LazyUiAccordionTrigger': typeof import("../components/Ui/accordion/AccordionTrigger.vue")['default']
    'LazyUiAlertDialog': typeof import("../components/Ui/alert-dialog/AlertDialog.vue")['default']
    'LazyUiAlertDialogAction': typeof import("../components/Ui/alert-dialog/AlertDialogAction.vue")['default']
    'LazyUiAlertDialogCancel': typeof import("../components/Ui/alert-dialog/AlertDialogCancel.vue")['default']
    'LazyUiAlertDialogContent': typeof import("../components/Ui/alert-dialog/AlertDialogContent.vue")['default']
    'LazyUiAlertDialogDescription': typeof import("../components/Ui/alert-dialog/AlertDialogDescription.vue")['default']
    'LazyUiAlertDialogFooter': typeof import("../components/Ui/alert-dialog/AlertDialogFooter.vue")['default']
    'LazyUiAlertDialogHeader': typeof import("../components/Ui/alert-dialog/AlertDialogHeader.vue")['default']
    'LazyUiAlertDialogTitle': typeof import("../components/Ui/alert-dialog/AlertDialogTitle.vue")['default']
    'LazyUiAlertDialogTrigger': typeof import("../components/Ui/alert-dialog/AlertDialogTrigger.vue")['default']
    'LazyUiAlert': typeof import("../components/Ui/alert/Alert.vue")['default']
    'LazyUiAlertDescription': typeof import("../components/Ui/alert/AlertDescription.vue")['default']
    'LazyUiAlertTitle': typeof import("../components/Ui/alert/AlertTitle.vue")['default']
    'LazyUiAspectRatio': typeof import("../components/Ui/aspect-ratio/AspectRatio.vue")['default']
    'LazyUiAvatar': typeof import("../components/Ui/avatar/Avatar.vue")['default']
    'LazyUiAvatarFallback': typeof import("../components/Ui/avatar/AvatarFallback.vue")['default']
    'LazyUiAvatarImage': typeof import("../components/Ui/avatar/AvatarImage.vue")['default']
    'LazyUiBadge': typeof import("../components/Ui/badge/Badge.vue")['default']
    'LazyUiBreadcrumb': typeof import("../components/Ui/breadcrumb/Breadcrumb.vue")['default']
    'LazyUiBreadcrumbEllipsis': typeof import("../components/Ui/breadcrumb/BreadcrumbEllipsis.vue")['default']
    'LazyUiBreadcrumbItem': typeof import("../components/Ui/breadcrumb/BreadcrumbItem.vue")['default']
    'LazyUiBreadcrumbLink': typeof import("../components/Ui/breadcrumb/BreadcrumbLink.vue")['default']
    'LazyUiBreadcrumbList': typeof import("../components/Ui/breadcrumb/BreadcrumbList.vue")['default']
    'LazyUiBreadcrumbPage': typeof import("../components/Ui/breadcrumb/BreadcrumbPage.vue")['default']
    'LazyUiBreadcrumbSeparator': typeof import("../components/Ui/breadcrumb/BreadcrumbSeparator.vue")['default']
    'LazyUiButton': typeof import("../components/Ui/button/Button.vue")['default']
    'LazyUiCalendar': typeof import("../components/Ui/calendar/Calendar.vue")['default']
    'LazyUiCalendarCell': typeof import("../components/Ui/calendar/CalendarCell.vue")['default']
    'LazyUiCalendarCellTrigger': typeof import("../components/Ui/calendar/CalendarCellTrigger.vue")['default']
    'LazyUiCalendarGrid': typeof import("../components/Ui/calendar/CalendarGrid.vue")['default']
    'LazyUiCalendarGridBody': typeof import("../components/Ui/calendar/CalendarGridBody.vue")['default']
    'LazyUiCalendarGridHead': typeof import("../components/Ui/calendar/CalendarGridHead.vue")['default']
    'LazyUiCalendarGridRow': typeof import("../components/Ui/calendar/CalendarGridRow.vue")['default']
    'LazyUiCalendarHeadCell': typeof import("../components/Ui/calendar/CalendarHeadCell.vue")['default']
    'LazyUiCalendarHeader': typeof import("../components/Ui/calendar/CalendarHeader.vue")['default']
    'LazyUiCalendarHeading': typeof import("../components/Ui/calendar/CalendarHeading.vue")['default']
    'LazyUiCalendarNextButton': typeof import("../components/Ui/calendar/CalendarNextButton.vue")['default']
    'LazyUiCalendarPrevButton': typeof import("../components/Ui/calendar/CalendarPrevButton.vue")['default']
    'LazyUiCarousel': typeof import("../components/Ui/carousel/Carousel.vue")['default']
    'LazyUiCarouselContent': typeof import("../components/Ui/carousel/CarouselContent.vue")['default']
    'LazyUiCarouselItem': typeof import("../components/Ui/carousel/CarouselItem.vue")['default']
    'LazyUiCarouselNext': typeof import("../components/Ui/carousel/CarouselNext.vue")['default']
    'LazyUiCarouselPrevious': typeof import("../components/Ui/carousel/CarouselPrevious.vue")['default']
    'LazyUiCarouselInterface': typeof import("../components/Ui/carousel/interface")['default']
    'LazyUiCarouselUseCarousel': typeof import("../components/Ui/carousel/useCarousel")['default']
    'LazyUiCheckbox': typeof import("../components/Ui/checkbox/Checkbox.vue")['default']
    'LazyUiChip': typeof import("../components/Ui/chip/Chip.vue")['default']
    'LazyUiDivider': typeof import("../components/Ui/divider/divider.vue")['default']
    'LazyUiDropfile': typeof import("../components/Ui/dropfile/Dropfile.vue")['default']
    'LazyUiHoverCard': typeof import("../components/Ui/hover-card/HoverCard.vue")['default']
    'LazyUiHoverCardContent': typeof import("../components/Ui/hover-card/HoverCardContent.vue")['default']
    'LazyUiHoverCardTrigger': typeof import("../components/Ui/hover-card/HoverCardTrigger.vue")['default']
    'LazyUiInput': typeof import("../components/Ui/input/Input.vue")['default']
    'LazyUiLabel': typeof import("../components/Ui/label/Label.vue")['default']
    'LazyUiPopover': typeof import("../components/Ui/popover/Popover.vue")['default']
    'LazyUiPopoverContent': typeof import("../components/Ui/popover/PopoverContent.vue")['default']
    'LazyUiPopoverTrigger': typeof import("../components/Ui/popover/PopoverTrigger.vue")['default']
    'LazyUiSelect': typeof import("../components/Ui/select/Select.vue")['default']
    'LazyUiSelectContent': typeof import("../components/Ui/select/SelectContent.vue")['default']
    'LazyUiSelectGroup': typeof import("../components/Ui/select/SelectGroup.vue")['default']
    'LazyUiSelectItem': typeof import("../components/Ui/select/SelectItem.vue")['default']
    'LazyUiSelectItemText': typeof import("../components/Ui/select/SelectItemText.vue")['default']
    'LazyUiSelectLabel': typeof import("../components/Ui/select/SelectLabel.vue")['default']
    'LazyUiSelectScrollDownButton': typeof import("../components/Ui/select/SelectScrollDownButton.vue")['default']
    'LazyUiSelectScrollUpButton': typeof import("../components/Ui/select/SelectScrollUpButton.vue")['default']
    'LazyUiSelectSeparator': typeof import("../components/Ui/select/SelectSeparator.vue")['default']
    'LazyUiSelectTrigger': typeof import("../components/Ui/select/SelectTrigger.vue")['default']
    'LazyUiSelectValue': typeof import("../components/Ui/select/SelectValue.vue")['default']
    'LazyUiSeparator': typeof import("../components/Ui/separator/Separator.vue")['default']
    'LazyUiToast': typeof import("../components/Ui/toast/Toast.vue")['default']
    'LazyUiToastAction': typeof import("../components/Ui/toast/ToastAction.vue")['default']
    'LazyUiToastClose': typeof import("../components/Ui/toast/ToastClose.vue")['default']
    'LazyUiToastDescription': typeof import("../components/Ui/toast/ToastDescription.vue")['default']
    'LazyUiToastProvider': typeof import("../components/Ui/toast/ToastProvider.vue")['default']
    'LazyUiToastTitle': typeof import("../components/Ui/toast/ToastTitle.vue")['default']
    'LazyUiToastViewport': typeof import("../components/Ui/toast/ToastViewport.vue")['default']
    'LazyUiToastToaster': typeof import("../components/Ui/toast/Toaster.vue")['default']
    'LazyUiToastUseToast': typeof import("../components/Ui/toast/use-toast")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/.pnpm/@nuxt+ui-templates@1.3.3/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyForm': typeof import("vee-validate")['Form']
    'LazyFormField': typeof import("vee-validate")['Field']
    'LazyPagination': typeof import("radix-vue")['PaginationRoot']
    'LazyPaginationList': typeof import("radix-vue")['PaginationList']
    'LazyPaginationListItem': typeof import("radix-vue")['PaginationListItem']
    'LazyAccordion': typeof import("../components/ui/accordion/index")['Accordion']
    'LazyAccordionContent': typeof import("../components/ui/accordion/index")['AccordionContent']
    'LazyAccordionItem': typeof import("../components/ui/accordion/index")['AccordionItem']
    'LazyAccordionTrigger': typeof import("../components/ui/accordion/index")['AccordionTrigger']
    'LazyAlert': typeof import("../components/ui/alert/index")['Alert']
    'LazyAlertTitle': typeof import("../components/ui/alert/index")['AlertTitle']
    'LazyAlertDescription': typeof import("../components/ui/alert/index")['AlertDescription']
    'LazyAlertDialog': typeof import("../components/ui/alert-dialog/index")['AlertDialog']
    'LazyAlertDialogTrigger': typeof import("../components/ui/alert-dialog/index")['AlertDialogTrigger']
    'LazyAlertDialogContent': typeof import("../components/ui/alert-dialog/index")['AlertDialogContent']
    'LazyAlertDialogHeader': typeof import("../components/ui/alert-dialog/index")['AlertDialogHeader']
    'LazyAlertDialogTitle': typeof import("../components/ui/alert-dialog/index")['AlertDialogTitle']
    'LazyAlertDialogDescription': typeof import("../components/ui/alert-dialog/index")['AlertDialogDescription']
    'LazyAlertDialogFooter': typeof import("../components/ui/alert-dialog/index")['AlertDialogFooter']
    'LazyAlertDialogAction': typeof import("../components/ui/alert-dialog/index")['AlertDialogAction']
    'LazyAlertDialogCancel': typeof import("../components/ui/alert-dialog/index")['AlertDialogCancel']
    'LazyAspectRatio': typeof import("../components/ui/aspect-ratio/index")['AspectRatio']
    'LazyAvatar': typeof import("../components/ui/avatar/index")['Avatar']
    'LazyAvatarImage': typeof import("../components/ui/avatar/index")['AvatarImage']
    'LazyAvatarFallback': typeof import("../components/ui/avatar/index")['AvatarFallback']
    'LazyBreadcrumb': typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
    'LazyBreadcrumbEllipsis': typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
    'LazyBreadcrumbItem': typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
    'LazyBreadcrumbLink': typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
    'LazyBreadcrumbList': typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
    'LazyBreadcrumbPage': typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
    'LazyBreadcrumbSeparator': typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
    'LazyButton': typeof import("../components/ui/button/index")['Button']
    'LazyCalendar': typeof import("../components/ui/calendar/index")['Calendar']
    'LazyCalendarCell': typeof import("../components/ui/calendar/index")['CalendarCell']
    'LazyCalendarCellTrigger': typeof import("../components/ui/calendar/index")['CalendarCellTrigger']
    'LazyCalendarGrid': typeof import("../components/ui/calendar/index")['CalendarGrid']
    'LazyCalendarGridBody': typeof import("../components/ui/calendar/index")['CalendarGridBody']
    'LazyCalendarGridHead': typeof import("../components/ui/calendar/index")['CalendarGridHead']
    'LazyCalendarGridRow': typeof import("../components/ui/calendar/index")['CalendarGridRow']
    'LazyCalendarHeadCell': typeof import("../components/ui/calendar/index")['CalendarHeadCell']
    'LazyCalendarHeader': typeof import("../components/ui/calendar/index")['CalendarHeader']
    'LazyCalendarHeading': typeof import("../components/ui/calendar/index")['CalendarHeading']
    'LazyCalendarNextButton': typeof import("../components/ui/calendar/index")['CalendarNextButton']
    'LazyCalendarPrevButton': typeof import("../components/ui/calendar/index")['CalendarPrevButton']
    'LazyCarousel': typeof import("../components/ui/carousel/index")['Carousel']
    'LazyCarouselContent': typeof import("../components/ui/carousel/index")['CarouselContent']
    'LazyCarouselItem': typeof import("../components/ui/carousel/index")['CarouselItem']
    'LazyCarouselPrevious': typeof import("../components/ui/carousel/index")['CarouselPrevious']
    'LazyCarouselNext': typeof import("../components/ui/carousel/index")['CarouselNext']
    'LazyCarouselApi': typeof import("../components/ui/carousel/index")['CarouselApi']
    'LazyCheckbox': typeof import("../components/ui/checkbox/index")['Checkbox']
    'LazyChip': typeof import("../components/ui/chip/index")['Chip']
    'LazyHoverCard': typeof import("../components/ui/hover-card/index")['HoverCard']
    'LazyHoverCardTrigger': typeof import("../components/ui/hover-card/index")['HoverCardTrigger']
    'LazyHoverCardContent': typeof import("../components/ui/hover-card/index")['HoverCardContent']
    'LazyInput': typeof import("../components/ui/input/index")['Input']
    'LazyLabel': typeof import("../components/ui/label/index")['Label']
    'LazyPopover': typeof import("../components/ui/popover/index")['Popover']
    'LazyPopoverTrigger': typeof import("../components/ui/popover/index")['PopoverTrigger']
    'LazyPopoverContent': typeof import("../components/ui/popover/index")['PopoverContent']
    'LazySelect': typeof import("../components/ui/select/index")['Select']
    'LazySelectValue': typeof import("../components/ui/select/index")['SelectValue']
    'LazySelectTrigger': typeof import("../components/ui/select/index")['SelectTrigger']
    'LazySelectContent': typeof import("../components/ui/select/index")['SelectContent']
    'LazySelectGroup': typeof import("../components/ui/select/index")['SelectGroup']
    'LazySelectItem': typeof import("../components/ui/select/index")['SelectItem']
    'LazySelectItemText': typeof import("../components/ui/select/index")['SelectItemText']
    'LazySelectLabel': typeof import("../components/ui/select/index")['SelectLabel']
    'LazySelectSeparator': typeof import("../components/ui/select/index")['SelectSeparator']
    'LazySelectScrollUpButton': typeof import("../components/ui/select/index")['SelectScrollUpButton']
    'LazySelectScrollDownButton': typeof import("../components/ui/select/index")['SelectScrollDownButton']
    'LazySeparator': typeof import("../components/ui/separator/index")['Separator']
    'LazyToaster': typeof import("../components/ui/toast/index")['Toaster']
    'LazyToast': typeof import("../components/ui/toast/index")['Toast']
    'LazyToastViewport': typeof import("../components/ui/toast/index")['ToastViewport']
    'LazyToastAction': typeof import("../components/ui/toast/index")['ToastAction']
    'LazyToastClose': typeof import("../components/ui/toast/index")['ToastClose']
    'LazyToastTitle': typeof import("../components/ui/toast/index")['ToastTitle']
    'LazyToastDescription': typeof import("../components/ui/toast/index")['ToastDescription']
    'LazyToastProvider': typeof import("../components/ui/toast/index")['ToastProvider']
    'LazyColorScheme': typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@3.4.1/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyIcon': typeof import("../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_vite@5.2.11_vue@3.4.26/node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyIconCSS': typeof import("../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_vite@5.2.11_vue@3.4.26/node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const UiAccordion: typeof import("../components/Ui/accordion/Accordion.vue")['default']
export const UiAccordionContent: typeof import("../components/Ui/accordion/AccordionContent.vue")['default']
export const UiAccordionItem: typeof import("../components/Ui/accordion/AccordionItem.vue")['default']
export const UiAccordionTrigger: typeof import("../components/Ui/accordion/AccordionTrigger.vue")['default']
export const UiAlertDialog: typeof import("../components/Ui/alert-dialog/AlertDialog.vue")['default']
export const UiAlertDialogAction: typeof import("../components/Ui/alert-dialog/AlertDialogAction.vue")['default']
export const UiAlertDialogCancel: typeof import("../components/Ui/alert-dialog/AlertDialogCancel.vue")['default']
export const UiAlertDialogContent: typeof import("../components/Ui/alert-dialog/AlertDialogContent.vue")['default']
export const UiAlertDialogDescription: typeof import("../components/Ui/alert-dialog/AlertDialogDescription.vue")['default']
export const UiAlertDialogFooter: typeof import("../components/Ui/alert-dialog/AlertDialogFooter.vue")['default']
export const UiAlertDialogHeader: typeof import("../components/Ui/alert-dialog/AlertDialogHeader.vue")['default']
export const UiAlertDialogTitle: typeof import("../components/Ui/alert-dialog/AlertDialogTitle.vue")['default']
export const UiAlertDialogTrigger: typeof import("../components/Ui/alert-dialog/AlertDialogTrigger.vue")['default']
export const UiAlert: typeof import("../components/Ui/alert/Alert.vue")['default']
export const UiAlertDescription: typeof import("../components/Ui/alert/AlertDescription.vue")['default']
export const UiAlertTitle: typeof import("../components/Ui/alert/AlertTitle.vue")['default']
export const UiAspectRatio: typeof import("../components/Ui/aspect-ratio/AspectRatio.vue")['default']
export const UiAvatar: typeof import("../components/Ui/avatar/Avatar.vue")['default']
export const UiAvatarFallback: typeof import("../components/Ui/avatar/AvatarFallback.vue")['default']
export const UiAvatarImage: typeof import("../components/Ui/avatar/AvatarImage.vue")['default']
export const UiBadge: typeof import("../components/Ui/badge/Badge.vue")['default']
export const UiBreadcrumb: typeof import("../components/Ui/breadcrumb/Breadcrumb.vue")['default']
export const UiBreadcrumbEllipsis: typeof import("../components/Ui/breadcrumb/BreadcrumbEllipsis.vue")['default']
export const UiBreadcrumbItem: typeof import("../components/Ui/breadcrumb/BreadcrumbItem.vue")['default']
export const UiBreadcrumbLink: typeof import("../components/Ui/breadcrumb/BreadcrumbLink.vue")['default']
export const UiBreadcrumbList: typeof import("../components/Ui/breadcrumb/BreadcrumbList.vue")['default']
export const UiBreadcrumbPage: typeof import("../components/Ui/breadcrumb/BreadcrumbPage.vue")['default']
export const UiBreadcrumbSeparator: typeof import("../components/Ui/breadcrumb/BreadcrumbSeparator.vue")['default']
export const UiButton: typeof import("../components/Ui/button/Button.vue")['default']
export const UiCalendar: typeof import("../components/Ui/calendar/Calendar.vue")['default']
export const UiCalendarCell: typeof import("../components/Ui/calendar/CalendarCell.vue")['default']
export const UiCalendarCellTrigger: typeof import("../components/Ui/calendar/CalendarCellTrigger.vue")['default']
export const UiCalendarGrid: typeof import("../components/Ui/calendar/CalendarGrid.vue")['default']
export const UiCalendarGridBody: typeof import("../components/Ui/calendar/CalendarGridBody.vue")['default']
export const UiCalendarGridHead: typeof import("../components/Ui/calendar/CalendarGridHead.vue")['default']
export const UiCalendarGridRow: typeof import("../components/Ui/calendar/CalendarGridRow.vue")['default']
export const UiCalendarHeadCell: typeof import("../components/Ui/calendar/CalendarHeadCell.vue")['default']
export const UiCalendarHeader: typeof import("../components/Ui/calendar/CalendarHeader.vue")['default']
export const UiCalendarHeading: typeof import("../components/Ui/calendar/CalendarHeading.vue")['default']
export const UiCalendarNextButton: typeof import("../components/Ui/calendar/CalendarNextButton.vue")['default']
export const UiCalendarPrevButton: typeof import("../components/Ui/calendar/CalendarPrevButton.vue")['default']
export const UiCarousel: typeof import("../components/Ui/carousel/Carousel.vue")['default']
export const UiCarouselContent: typeof import("../components/Ui/carousel/CarouselContent.vue")['default']
export const UiCarouselItem: typeof import("../components/Ui/carousel/CarouselItem.vue")['default']
export const UiCarouselNext: typeof import("../components/Ui/carousel/CarouselNext.vue")['default']
export const UiCarouselPrevious: typeof import("../components/Ui/carousel/CarouselPrevious.vue")['default']
export const UiCarouselInterface: typeof import("../components/Ui/carousel/interface")['default']
export const UiCarouselUseCarousel: typeof import("../components/Ui/carousel/useCarousel")['default']
export const UiCheckbox: typeof import("../components/Ui/checkbox/Checkbox.vue")['default']
export const UiChip: typeof import("../components/Ui/chip/Chip.vue")['default']
export const UiDivider: typeof import("../components/Ui/divider/divider.vue")['default']
export const UiDropfile: typeof import("../components/Ui/dropfile/Dropfile.vue")['default']
export const UiHoverCard: typeof import("../components/Ui/hover-card/HoverCard.vue")['default']
export const UiHoverCardContent: typeof import("../components/Ui/hover-card/HoverCardContent.vue")['default']
export const UiHoverCardTrigger: typeof import("../components/Ui/hover-card/HoverCardTrigger.vue")['default']
export const UiInput: typeof import("../components/Ui/input/Input.vue")['default']
export const UiLabel: typeof import("../components/Ui/label/Label.vue")['default']
export const UiPopover: typeof import("../components/Ui/popover/Popover.vue")['default']
export const UiPopoverContent: typeof import("../components/Ui/popover/PopoverContent.vue")['default']
export const UiPopoverTrigger: typeof import("../components/Ui/popover/PopoverTrigger.vue")['default']
export const UiSelect: typeof import("../components/Ui/select/Select.vue")['default']
export const UiSelectContent: typeof import("../components/Ui/select/SelectContent.vue")['default']
export const UiSelectGroup: typeof import("../components/Ui/select/SelectGroup.vue")['default']
export const UiSelectItem: typeof import("../components/Ui/select/SelectItem.vue")['default']
export const UiSelectItemText: typeof import("../components/Ui/select/SelectItemText.vue")['default']
export const UiSelectLabel: typeof import("../components/Ui/select/SelectLabel.vue")['default']
export const UiSelectScrollDownButton: typeof import("../components/Ui/select/SelectScrollDownButton.vue")['default']
export const UiSelectScrollUpButton: typeof import("../components/Ui/select/SelectScrollUpButton.vue")['default']
export const UiSelectSeparator: typeof import("../components/Ui/select/SelectSeparator.vue")['default']
export const UiSelectTrigger: typeof import("../components/Ui/select/SelectTrigger.vue")['default']
export const UiSelectValue: typeof import("../components/Ui/select/SelectValue.vue")['default']
export const UiSeparator: typeof import("../components/Ui/separator/Separator.vue")['default']
export const UiToast: typeof import("../components/Ui/toast/Toast.vue")['default']
export const UiToastAction: typeof import("../components/Ui/toast/ToastAction.vue")['default']
export const UiToastClose: typeof import("../components/Ui/toast/ToastClose.vue")['default']
export const UiToastDescription: typeof import("../components/Ui/toast/ToastDescription.vue")['default']
export const UiToastProvider: typeof import("../components/Ui/toast/ToastProvider.vue")['default']
export const UiToastTitle: typeof import("../components/Ui/toast/ToastTitle.vue")['default']
export const UiToastViewport: typeof import("../components/Ui/toast/ToastViewport.vue")['default']
export const UiToastToaster: typeof import("../components/Ui/toast/Toaster.vue")['default']
export const UiToastUseToast: typeof import("../components/Ui/toast/use-toast")['default']
export const NuxtWelcome: typeof import("../node_modules/.pnpm/@nuxt+ui-templates@1.3.3/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Form: typeof import("vee-validate")['Form']
export const FormField: typeof import("vee-validate")['Field']
export const Pagination: typeof import("radix-vue")['PaginationRoot']
export const PaginationList: typeof import("radix-vue")['PaginationList']
export const PaginationListItem: typeof import("radix-vue")['PaginationListItem']
export const Accordion: typeof import("../components/ui/accordion/index")['Accordion']
export const AccordionContent: typeof import("../components/ui/accordion/index")['AccordionContent']
export const AccordionItem: typeof import("../components/ui/accordion/index")['AccordionItem']
export const AccordionTrigger: typeof import("../components/ui/accordion/index")['AccordionTrigger']
export const Alert: typeof import("../components/ui/alert/index")['Alert']
export const AlertTitle: typeof import("../components/ui/alert/index")['AlertTitle']
export const AlertDescription: typeof import("../components/ui/alert/index")['AlertDescription']
export const AlertDialog: typeof import("../components/ui/alert-dialog/index")['AlertDialog']
export const AlertDialogTrigger: typeof import("../components/ui/alert-dialog/index")['AlertDialogTrigger']
export const AlertDialogContent: typeof import("../components/ui/alert-dialog/index")['AlertDialogContent']
export const AlertDialogHeader: typeof import("../components/ui/alert-dialog/index")['AlertDialogHeader']
export const AlertDialogTitle: typeof import("../components/ui/alert-dialog/index")['AlertDialogTitle']
export const AlertDialogDescription: typeof import("../components/ui/alert-dialog/index")['AlertDialogDescription']
export const AlertDialogFooter: typeof import("../components/ui/alert-dialog/index")['AlertDialogFooter']
export const AlertDialogAction: typeof import("../components/ui/alert-dialog/index")['AlertDialogAction']
export const AlertDialogCancel: typeof import("../components/ui/alert-dialog/index")['AlertDialogCancel']
export const AspectRatio: typeof import("../components/ui/aspect-ratio/index")['AspectRatio']
export const Avatar: typeof import("../components/ui/avatar/index")['Avatar']
export const AvatarImage: typeof import("../components/ui/avatar/index")['AvatarImage']
export const AvatarFallback: typeof import("../components/ui/avatar/index")['AvatarFallback']
export const Breadcrumb: typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
export const BreadcrumbEllipsis: typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
export const BreadcrumbItem: typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
export const BreadcrumbLink: typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
export const BreadcrumbList: typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
export const BreadcrumbPage: typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
export const BreadcrumbSeparator: typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
export const Button: typeof import("../components/ui/button/index")['Button']
export const Calendar: typeof import("../components/ui/calendar/index")['Calendar']
export const CalendarCell: typeof import("../components/ui/calendar/index")['CalendarCell']
export const CalendarCellTrigger: typeof import("../components/ui/calendar/index")['CalendarCellTrigger']
export const CalendarGrid: typeof import("../components/ui/calendar/index")['CalendarGrid']
export const CalendarGridBody: typeof import("../components/ui/calendar/index")['CalendarGridBody']
export const CalendarGridHead: typeof import("../components/ui/calendar/index")['CalendarGridHead']
export const CalendarGridRow: typeof import("../components/ui/calendar/index")['CalendarGridRow']
export const CalendarHeadCell: typeof import("../components/ui/calendar/index")['CalendarHeadCell']
export const CalendarHeader: typeof import("../components/ui/calendar/index")['CalendarHeader']
export const CalendarHeading: typeof import("../components/ui/calendar/index")['CalendarHeading']
export const CalendarNextButton: typeof import("../components/ui/calendar/index")['CalendarNextButton']
export const CalendarPrevButton: typeof import("../components/ui/calendar/index")['CalendarPrevButton']
export const Carousel: typeof import("../components/ui/carousel/index")['Carousel']
export const CarouselContent: typeof import("../components/ui/carousel/index")['CarouselContent']
export const CarouselItem: typeof import("../components/ui/carousel/index")['CarouselItem']
export const CarouselPrevious: typeof import("../components/ui/carousel/index")['CarouselPrevious']
export const CarouselNext: typeof import("../components/ui/carousel/index")['CarouselNext']
export const CarouselApi: typeof import("../components/ui/carousel/index")['CarouselApi']
export const Checkbox: typeof import("../components/ui/checkbox/index")['Checkbox']
export const Chip: typeof import("../components/ui/chip/index")['Chip']
export const HoverCard: typeof import("../components/ui/hover-card/index")['HoverCard']
export const HoverCardTrigger: typeof import("../components/ui/hover-card/index")['HoverCardTrigger']
export const HoverCardContent: typeof import("../components/ui/hover-card/index")['HoverCardContent']
export const Input: typeof import("../components/ui/input/index")['Input']
export const Label: typeof import("../components/ui/label/index")['Label']
export const Popover: typeof import("../components/ui/popover/index")['Popover']
export const PopoverTrigger: typeof import("../components/ui/popover/index")['PopoverTrigger']
export const PopoverContent: typeof import("../components/ui/popover/index")['PopoverContent']
export const Select: typeof import("../components/ui/select/index")['Select']
export const SelectValue: typeof import("../components/ui/select/index")['SelectValue']
export const SelectTrigger: typeof import("../components/ui/select/index")['SelectTrigger']
export const SelectContent: typeof import("../components/ui/select/index")['SelectContent']
export const SelectGroup: typeof import("../components/ui/select/index")['SelectGroup']
export const SelectItem: typeof import("../components/ui/select/index")['SelectItem']
export const SelectItemText: typeof import("../components/ui/select/index")['SelectItemText']
export const SelectLabel: typeof import("../components/ui/select/index")['SelectLabel']
export const SelectSeparator: typeof import("../components/ui/select/index")['SelectSeparator']
export const SelectScrollUpButton: typeof import("../components/ui/select/index")['SelectScrollUpButton']
export const SelectScrollDownButton: typeof import("../components/ui/select/index")['SelectScrollDownButton']
export const Separator: typeof import("../components/ui/separator/index")['Separator']
export const Toaster: typeof import("../components/ui/toast/index")['Toaster']
export const Toast: typeof import("../components/ui/toast/index")['Toast']
export const ToastViewport: typeof import("../components/ui/toast/index")['ToastViewport']
export const ToastAction: typeof import("../components/ui/toast/index")['ToastAction']
export const ToastClose: typeof import("../components/ui/toast/index")['ToastClose']
export const ToastTitle: typeof import("../components/ui/toast/index")['ToastTitle']
export const ToastDescription: typeof import("../components/ui/toast/index")['ToastDescription']
export const ToastProvider: typeof import("../components/ui/toast/index")['ToastProvider']
export const ColorScheme: typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@3.4.1/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const Icon: typeof import("../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_vite@5.2.11_vue@3.4.26/node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_vite@5.2.11_vue@3.4.26/node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const NuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyUiAccordion: typeof import("../components/Ui/accordion/Accordion.vue")['default']
export const LazyUiAccordionContent: typeof import("../components/Ui/accordion/AccordionContent.vue")['default']
export const LazyUiAccordionItem: typeof import("../components/Ui/accordion/AccordionItem.vue")['default']
export const LazyUiAccordionTrigger: typeof import("../components/Ui/accordion/AccordionTrigger.vue")['default']
export const LazyUiAlertDialog: typeof import("../components/Ui/alert-dialog/AlertDialog.vue")['default']
export const LazyUiAlertDialogAction: typeof import("../components/Ui/alert-dialog/AlertDialogAction.vue")['default']
export const LazyUiAlertDialogCancel: typeof import("../components/Ui/alert-dialog/AlertDialogCancel.vue")['default']
export const LazyUiAlertDialogContent: typeof import("../components/Ui/alert-dialog/AlertDialogContent.vue")['default']
export const LazyUiAlertDialogDescription: typeof import("../components/Ui/alert-dialog/AlertDialogDescription.vue")['default']
export const LazyUiAlertDialogFooter: typeof import("../components/Ui/alert-dialog/AlertDialogFooter.vue")['default']
export const LazyUiAlertDialogHeader: typeof import("../components/Ui/alert-dialog/AlertDialogHeader.vue")['default']
export const LazyUiAlertDialogTitle: typeof import("../components/Ui/alert-dialog/AlertDialogTitle.vue")['default']
export const LazyUiAlertDialogTrigger: typeof import("../components/Ui/alert-dialog/AlertDialogTrigger.vue")['default']
export const LazyUiAlert: typeof import("../components/Ui/alert/Alert.vue")['default']
export const LazyUiAlertDescription: typeof import("../components/Ui/alert/AlertDescription.vue")['default']
export const LazyUiAlertTitle: typeof import("../components/Ui/alert/AlertTitle.vue")['default']
export const LazyUiAspectRatio: typeof import("../components/Ui/aspect-ratio/AspectRatio.vue")['default']
export const LazyUiAvatar: typeof import("../components/Ui/avatar/Avatar.vue")['default']
export const LazyUiAvatarFallback: typeof import("../components/Ui/avatar/AvatarFallback.vue")['default']
export const LazyUiAvatarImage: typeof import("../components/Ui/avatar/AvatarImage.vue")['default']
export const LazyUiBadge: typeof import("../components/Ui/badge/Badge.vue")['default']
export const LazyUiBreadcrumb: typeof import("../components/Ui/breadcrumb/Breadcrumb.vue")['default']
export const LazyUiBreadcrumbEllipsis: typeof import("../components/Ui/breadcrumb/BreadcrumbEllipsis.vue")['default']
export const LazyUiBreadcrumbItem: typeof import("../components/Ui/breadcrumb/BreadcrumbItem.vue")['default']
export const LazyUiBreadcrumbLink: typeof import("../components/Ui/breadcrumb/BreadcrumbLink.vue")['default']
export const LazyUiBreadcrumbList: typeof import("../components/Ui/breadcrumb/BreadcrumbList.vue")['default']
export const LazyUiBreadcrumbPage: typeof import("../components/Ui/breadcrumb/BreadcrumbPage.vue")['default']
export const LazyUiBreadcrumbSeparator: typeof import("../components/Ui/breadcrumb/BreadcrumbSeparator.vue")['default']
export const LazyUiButton: typeof import("../components/Ui/button/Button.vue")['default']
export const LazyUiCalendar: typeof import("../components/Ui/calendar/Calendar.vue")['default']
export const LazyUiCalendarCell: typeof import("../components/Ui/calendar/CalendarCell.vue")['default']
export const LazyUiCalendarCellTrigger: typeof import("../components/Ui/calendar/CalendarCellTrigger.vue")['default']
export const LazyUiCalendarGrid: typeof import("../components/Ui/calendar/CalendarGrid.vue")['default']
export const LazyUiCalendarGridBody: typeof import("../components/Ui/calendar/CalendarGridBody.vue")['default']
export const LazyUiCalendarGridHead: typeof import("../components/Ui/calendar/CalendarGridHead.vue")['default']
export const LazyUiCalendarGridRow: typeof import("../components/Ui/calendar/CalendarGridRow.vue")['default']
export const LazyUiCalendarHeadCell: typeof import("../components/Ui/calendar/CalendarHeadCell.vue")['default']
export const LazyUiCalendarHeader: typeof import("../components/Ui/calendar/CalendarHeader.vue")['default']
export const LazyUiCalendarHeading: typeof import("../components/Ui/calendar/CalendarHeading.vue")['default']
export const LazyUiCalendarNextButton: typeof import("../components/Ui/calendar/CalendarNextButton.vue")['default']
export const LazyUiCalendarPrevButton: typeof import("../components/Ui/calendar/CalendarPrevButton.vue")['default']
export const LazyUiCarousel: typeof import("../components/Ui/carousel/Carousel.vue")['default']
export const LazyUiCarouselContent: typeof import("../components/Ui/carousel/CarouselContent.vue")['default']
export const LazyUiCarouselItem: typeof import("../components/Ui/carousel/CarouselItem.vue")['default']
export const LazyUiCarouselNext: typeof import("../components/Ui/carousel/CarouselNext.vue")['default']
export const LazyUiCarouselPrevious: typeof import("../components/Ui/carousel/CarouselPrevious.vue")['default']
export const LazyUiCarouselInterface: typeof import("../components/Ui/carousel/interface")['default']
export const LazyUiCarouselUseCarousel: typeof import("../components/Ui/carousel/useCarousel")['default']
export const LazyUiCheckbox: typeof import("../components/Ui/checkbox/Checkbox.vue")['default']
export const LazyUiChip: typeof import("../components/Ui/chip/Chip.vue")['default']
export const LazyUiDivider: typeof import("../components/Ui/divider/divider.vue")['default']
export const LazyUiDropfile: typeof import("../components/Ui/dropfile/Dropfile.vue")['default']
export const LazyUiHoverCard: typeof import("../components/Ui/hover-card/HoverCard.vue")['default']
export const LazyUiHoverCardContent: typeof import("../components/Ui/hover-card/HoverCardContent.vue")['default']
export const LazyUiHoverCardTrigger: typeof import("../components/Ui/hover-card/HoverCardTrigger.vue")['default']
export const LazyUiInput: typeof import("../components/Ui/input/Input.vue")['default']
export const LazyUiLabel: typeof import("../components/Ui/label/Label.vue")['default']
export const LazyUiPopover: typeof import("../components/Ui/popover/Popover.vue")['default']
export const LazyUiPopoverContent: typeof import("../components/Ui/popover/PopoverContent.vue")['default']
export const LazyUiPopoverTrigger: typeof import("../components/Ui/popover/PopoverTrigger.vue")['default']
export const LazyUiSelect: typeof import("../components/Ui/select/Select.vue")['default']
export const LazyUiSelectContent: typeof import("../components/Ui/select/SelectContent.vue")['default']
export const LazyUiSelectGroup: typeof import("../components/Ui/select/SelectGroup.vue")['default']
export const LazyUiSelectItem: typeof import("../components/Ui/select/SelectItem.vue")['default']
export const LazyUiSelectItemText: typeof import("../components/Ui/select/SelectItemText.vue")['default']
export const LazyUiSelectLabel: typeof import("../components/Ui/select/SelectLabel.vue")['default']
export const LazyUiSelectScrollDownButton: typeof import("../components/Ui/select/SelectScrollDownButton.vue")['default']
export const LazyUiSelectScrollUpButton: typeof import("../components/Ui/select/SelectScrollUpButton.vue")['default']
export const LazyUiSelectSeparator: typeof import("../components/Ui/select/SelectSeparator.vue")['default']
export const LazyUiSelectTrigger: typeof import("../components/Ui/select/SelectTrigger.vue")['default']
export const LazyUiSelectValue: typeof import("../components/Ui/select/SelectValue.vue")['default']
export const LazyUiSeparator: typeof import("../components/Ui/separator/Separator.vue")['default']
export const LazyUiToast: typeof import("../components/Ui/toast/Toast.vue")['default']
export const LazyUiToastAction: typeof import("../components/Ui/toast/ToastAction.vue")['default']
export const LazyUiToastClose: typeof import("../components/Ui/toast/ToastClose.vue")['default']
export const LazyUiToastDescription: typeof import("../components/Ui/toast/ToastDescription.vue")['default']
export const LazyUiToastProvider: typeof import("../components/Ui/toast/ToastProvider.vue")['default']
export const LazyUiToastTitle: typeof import("../components/Ui/toast/ToastTitle.vue")['default']
export const LazyUiToastViewport: typeof import("../components/Ui/toast/ToastViewport.vue")['default']
export const LazyUiToastToaster: typeof import("../components/Ui/toast/Toaster.vue")['default']
export const LazyUiToastUseToast: typeof import("../components/Ui/toast/use-toast")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/.pnpm/@nuxt+ui-templates@1.3.3/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyForm: typeof import("vee-validate")['Form']
export const LazyFormField: typeof import("vee-validate")['Field']
export const LazyPagination: typeof import("radix-vue")['PaginationRoot']
export const LazyPaginationList: typeof import("radix-vue")['PaginationList']
export const LazyPaginationListItem: typeof import("radix-vue")['PaginationListItem']
export const LazyAccordion: typeof import("../components/ui/accordion/index")['Accordion']
export const LazyAccordionContent: typeof import("../components/ui/accordion/index")['AccordionContent']
export const LazyAccordionItem: typeof import("../components/ui/accordion/index")['AccordionItem']
export const LazyAccordionTrigger: typeof import("../components/ui/accordion/index")['AccordionTrigger']
export const LazyAlert: typeof import("../components/ui/alert/index")['Alert']
export const LazyAlertTitle: typeof import("../components/ui/alert/index")['AlertTitle']
export const LazyAlertDescription: typeof import("../components/ui/alert/index")['AlertDescription']
export const LazyAlertDialog: typeof import("../components/ui/alert-dialog/index")['AlertDialog']
export const LazyAlertDialogTrigger: typeof import("../components/ui/alert-dialog/index")['AlertDialogTrigger']
export const LazyAlertDialogContent: typeof import("../components/ui/alert-dialog/index")['AlertDialogContent']
export const LazyAlertDialogHeader: typeof import("../components/ui/alert-dialog/index")['AlertDialogHeader']
export const LazyAlertDialogTitle: typeof import("../components/ui/alert-dialog/index")['AlertDialogTitle']
export const LazyAlertDialogDescription: typeof import("../components/ui/alert-dialog/index")['AlertDialogDescription']
export const LazyAlertDialogFooter: typeof import("../components/ui/alert-dialog/index")['AlertDialogFooter']
export const LazyAlertDialogAction: typeof import("../components/ui/alert-dialog/index")['AlertDialogAction']
export const LazyAlertDialogCancel: typeof import("../components/ui/alert-dialog/index")['AlertDialogCancel']
export const LazyAspectRatio: typeof import("../components/ui/aspect-ratio/index")['AspectRatio']
export const LazyAvatar: typeof import("../components/ui/avatar/index")['Avatar']
export const LazyAvatarImage: typeof import("../components/ui/avatar/index")['AvatarImage']
export const LazyAvatarFallback: typeof import("../components/ui/avatar/index")['AvatarFallback']
export const LazyBreadcrumb: typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
export const LazyBreadcrumbEllipsis: typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
export const LazyBreadcrumbItem: typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
export const LazyBreadcrumbLink: typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
export const LazyBreadcrumbList: typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
export const LazyBreadcrumbPage: typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
export const LazyBreadcrumbSeparator: typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
export const LazyButton: typeof import("../components/ui/button/index")['Button']
export const LazyCalendar: typeof import("../components/ui/calendar/index")['Calendar']
export const LazyCalendarCell: typeof import("../components/ui/calendar/index")['CalendarCell']
export const LazyCalendarCellTrigger: typeof import("../components/ui/calendar/index")['CalendarCellTrigger']
export const LazyCalendarGrid: typeof import("../components/ui/calendar/index")['CalendarGrid']
export const LazyCalendarGridBody: typeof import("../components/ui/calendar/index")['CalendarGridBody']
export const LazyCalendarGridHead: typeof import("../components/ui/calendar/index")['CalendarGridHead']
export const LazyCalendarGridRow: typeof import("../components/ui/calendar/index")['CalendarGridRow']
export const LazyCalendarHeadCell: typeof import("../components/ui/calendar/index")['CalendarHeadCell']
export const LazyCalendarHeader: typeof import("../components/ui/calendar/index")['CalendarHeader']
export const LazyCalendarHeading: typeof import("../components/ui/calendar/index")['CalendarHeading']
export const LazyCalendarNextButton: typeof import("../components/ui/calendar/index")['CalendarNextButton']
export const LazyCalendarPrevButton: typeof import("../components/ui/calendar/index")['CalendarPrevButton']
export const LazyCarousel: typeof import("../components/ui/carousel/index")['Carousel']
export const LazyCarouselContent: typeof import("../components/ui/carousel/index")['CarouselContent']
export const LazyCarouselItem: typeof import("../components/ui/carousel/index")['CarouselItem']
export const LazyCarouselPrevious: typeof import("../components/ui/carousel/index")['CarouselPrevious']
export const LazyCarouselNext: typeof import("../components/ui/carousel/index")['CarouselNext']
export const LazyCarouselApi: typeof import("../components/ui/carousel/index")['CarouselApi']
export const LazyCheckbox: typeof import("../components/ui/checkbox/index")['Checkbox']
export const LazyChip: typeof import("../components/ui/chip/index")['Chip']
export const LazyHoverCard: typeof import("../components/ui/hover-card/index")['HoverCard']
export const LazyHoverCardTrigger: typeof import("../components/ui/hover-card/index")['HoverCardTrigger']
export const LazyHoverCardContent: typeof import("../components/ui/hover-card/index")['HoverCardContent']
export const LazyInput: typeof import("../components/ui/input/index")['Input']
export const LazyLabel: typeof import("../components/ui/label/index")['Label']
export const LazyPopover: typeof import("../components/ui/popover/index")['Popover']
export const LazyPopoverTrigger: typeof import("../components/ui/popover/index")['PopoverTrigger']
export const LazyPopoverContent: typeof import("../components/ui/popover/index")['PopoverContent']
export const LazySelect: typeof import("../components/ui/select/index")['Select']
export const LazySelectValue: typeof import("../components/ui/select/index")['SelectValue']
export const LazySelectTrigger: typeof import("../components/ui/select/index")['SelectTrigger']
export const LazySelectContent: typeof import("../components/ui/select/index")['SelectContent']
export const LazySelectGroup: typeof import("../components/ui/select/index")['SelectGroup']
export const LazySelectItem: typeof import("../components/ui/select/index")['SelectItem']
export const LazySelectItemText: typeof import("../components/ui/select/index")['SelectItemText']
export const LazySelectLabel: typeof import("../components/ui/select/index")['SelectLabel']
export const LazySelectSeparator: typeof import("../components/ui/select/index")['SelectSeparator']
export const LazySelectScrollUpButton: typeof import("../components/ui/select/index")['SelectScrollUpButton']
export const LazySelectScrollDownButton: typeof import("../components/ui/select/index")['SelectScrollDownButton']
export const LazySeparator: typeof import("../components/ui/separator/index")['Separator']
export const LazyToaster: typeof import("../components/ui/toast/index")['Toaster']
export const LazyToast: typeof import("../components/ui/toast/index")['Toast']
export const LazyToastViewport: typeof import("../components/ui/toast/index")['ToastViewport']
export const LazyToastAction: typeof import("../components/ui/toast/index")['ToastAction']
export const LazyToastClose: typeof import("../components/ui/toast/index")['ToastClose']
export const LazyToastTitle: typeof import("../components/ui/toast/index")['ToastTitle']
export const LazyToastDescription: typeof import("../components/ui/toast/index")['ToastDescription']
export const LazyToastProvider: typeof import("../components/ui/toast/index")['ToastProvider']
export const LazyColorScheme: typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@3.4.1/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyIcon: typeof import("../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_vite@5.2.11_vue@3.4.26/node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyIconCSS: typeof import("../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_vite@5.2.11_vue@3.4.26/node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@unocss+reset@0.59.4_floating-vue@5.2.2_typescript@5.4.5_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
